import Head from 'next/head';
import Image from 'next/image';
import NavBar from '@/components/NavBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>George | Full-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    </>
  );
}
